map_tiles:
  - label: GBIF
    attribution: '&copy; <a href="https://gbif.org">Based on GBIF.org</a>'
    server: https://tile.gbif.org/3857/omt/{z}/{x}/{y}{r}.png?style=gbif-natural-en
    zoomOffset: -1
    tileSize: 512
    minZoom: 1
    maxZoom: 18
    dpr:
      1: '@1x'
#  - label: OpenStreetMap
#    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
#    server: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
